### ISSUE TITLE
Having only DS18B20_ERROR_COMM

### ISSUE THREAD

**Issue by TheAce58** [Jacajack/avr-dallas1820#7]
Hello,

I spent some times on this library to know how to use it, but I'm still having the same error.

I saw the issue of @IMAN4K.

To remove this error, simply add the `F_CPU `define to all files that contain the `util/delay.h` library

Of course, this define must be added before calling the` util/delay.h` include.

Exemple : 
`#define F_CPU 16000000UL
#include <util/delay.h>`

This means that the correct `F_CPU define` must be added to the :
- `ds18b20.c`
- `onewire.c`
- and of course `main.py`

Here it is, I hope it will help some people, so they don't waste time.

**TheAce58**

**Comment by Jacajack** [comment]
Hello,

That's right, though manually adding the same definition in multiple compilation units seems like a very error-prone approach to me. Keep in mind that the `F_CPU`  macro must have the same value everywhere. That's why it might be a better idea to add it as a compiler flag (`-DF_CPU=16000000UL`) in a single place like `makefile`.

I'll close this issue, since it refers to the same problem as #1. I'll mark both issues as frequently asked questions.
